/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NZCPJNI */

#ifndef _Included_NZCPJNI
#define _Included_NZCPJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NZCPJNI
 * Method:    verify_pass_uri
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_NZCPJNI_verify_1pass_1uri
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
