#!/bin/bash
export INCL_1=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.0.0/include
export INCL_2=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
export INCL_3=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include


cppcheck \
    -I $INCL_1 \
    -I $INCL_2 \
    -I compiled/usr/local/include \
    -I . \
    -isweet-b-master\
    -itinycbor-main\
    --suppress=*:compiled/usr/local/include/* \
    --inline-suppr \
    --enable=all --inconclusive --library=posix \
    -U __WINT_TYPE__\
    -U __WCHAR_TYPE__\
    -U __SIZE_TYPE__\
    -U __PTRDIFF_TYPE__\
    --force \
    .